# Worksheet 04

Name:  Jingbo Wang
UID: U04536921

### Topics

- Distance & Similarity

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

p is the power parameter. d determines the dimensionality of the points to be calculated.

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

Euclidean distance is when p=2 in the minkowski distance, Manhattan is when p=1.

Conceptually in a space, Euclidean distance is the shortest straight path between the two points, whereas Manhattan is like the shortest path walking along a grid.

Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

The largest difference between coordinates will be gradually more weighted when p increases. In this case it would be 1 for point A and B, therefore the distance will tend to be 1 as p grows to infinity.

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

No. We're using an example where p=1/2, points A(0,0), B(1,0), C(0,1). The distance between B, C will be greater than the sum of distances between AB and AC, this violates the triangle inequality required by distance functions.

e) when would you use cosine similarity over the euclidan distance?

When direction matters more than magnitude.

f) what does the jaccard distance account for that the manhattan distance doesn't?

Jaccard distance takes in account the size of similarities (intersection) when making comparisons.

#### Part 2

Consider the following two sentences:

In [1]:
s1 = "hello my name is Alice"
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [2]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [3]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['Alice', 'my', 'hello', 'name', 'is', 'Bob']
[1, 1, 1, 1, 1, 0]


Let's add a new sentence to our corpus:

In [20]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [5]:
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)

['hi', 'Alice', 'my', 'hello', 'name', 'is', 'Bob', 'Claude']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [6]:
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)
v2 = [1 if x in s2 else 0 for x in all_words]
print(v2)
v3 = [1 if x in s3 else 0 for x in all_words]
print(v3)

[0, 1, 1, 1, 1, 1, 0, 0]
[0, 0, 1, 1, 1, 1, 1, 0]
[1, 0, 1, 0, 1, 1, 0, 1]


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [7]:
def Manhattan_Distance(vec1: list, vec2: list):
    if len(vec1)!=len(vec2):
        raise ValueError("the vectors must be in the same dimensional space")
    s=0.0
    for i in range(len(vec1)):
        s+= abs(vec1[i]-vec2[i])
    return s

print(Manhattan_Distance(v1,v2))
print(Manhattan_Distance(v1,v3))
print(Manhattan_Distance(v2,v3))

2.0
4.0
4.0


v1 and v2 are the most similar using Manhattan distance function.

d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [8]:
corpus = ["hi Alice", "hello Claude", "Bob my name is Claude", "hi Claude my name is Alice", "hello Bob"]
all_words = list(set([item for x in corpus for item in x.split()]))
vectorized_corpus = [[1 if x in s else 0 for x in all_words] for s in corpus]
print(vectorized_corpus)

[[1, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 1], [0, 0, 1, 0, 1, 1, 1, 1], [1, 1, 1, 0, 1, 1, 0, 1], [0, 0, 0, 1, 0, 0, 1, 0]]


e) How many rows and columns does this matrix have?

In [9]:
row = len(vectorized_corpus)
col = len(vectorized_corpus[0])
print("#row = ",row)
print("#col = ",col)

#row =  5
#col =  8


f) When using the Manhattan distance, which two sentences are the most similar?

In [11]:
mini, minj = 0,0
mindst = 500
for i in range(row):
    for j in range(i+1,row):
        d = Manhattan_Distance(vectorized_corpus[i],vectorized_corpus[j])
        if d<mindst:
            mini,minj = i,j
            mindst = d
print(mini,minj,mindst)

1 4 2.0


The second and fifth sentences are the most similar(since python list starts from 0 index).

#### Part 3 Challenge

Given a set of graphs $\mathcal{G}$, each graph $G \in \mathcal{G}$ is defined over the same set of nodes $V$. The graphs are represented by their adjacency matrices, which are 2D arrays where each element indicates whether a pair of nodes is connected by an edge.

Your task is to compute the pairwise distances between these graphs based on a specific distance metric. The distance $d(G, G')$ between two graphs $G = (V, E)$ and $G' = (V, E')$ is defined as the sum of the number of edges in $G$ but not in $G'$, and the number of edges in $G'$ but not in $G$. Mathematically, this can be expressed as:

$$
d(G, G') = |E \setminus E'| + |E' \setminus E|.
$$

##### Requirements:
1. **Input**: Should take a list of 2D numpy arrays as input. Each array represents the adjacency matrix of a graph.

2. **Output**: Should output a pairwise distance matrix. If there are $n$ graphs in the input list, the output should be an $n \times n$ matrix where the entry at position $(i, j)$ represents the distance between the $i^{th}$ and $j^{th}$ graph.

In [15]:
import numpy as np

# Function to compute the distance between two graphs
def graph_distance(G, G_prime):
    diff = np.logical_xor(G, G_prime)
    return np.sum(diff)

# Function to compute pairwise distances between graphs
def pairwise_graph_distances(graphs):
    n = len(graphs)

    distance_matrix = np.zeros((n, n))

    for i in range(n):
        for j in range(i + 1, n):
            distance = graph_distance(graphs[i], graphs[j])
            distance_matrix[i, j] = distance_matrix[j, i] = distance
    return distance_matrix

In [19]:
graph1 = np.array([[0, 1, 0, 0, 1],
                   [1, 0, 1, 0, 0],
                   [0, 1, 0, 1, 0],
                   [0, 0, 1, 0, 1],
                   [1, 0, 0, 1, 0]])

graph2 = np.array([[0, 0, 1, 0, 1],
                   [0, 0, 0, 1, 0],
                   [1, 0, 0, 0, 1],
                   [0, 1, 0, 0, 0],
                   [1, 0, 1, 0, 0]])

graph3 = np.array([[0, 1, 1, 0, 0],
                   [1, 0, 0, 1, 0],
                   [1, 0, 0, 1, 1],
                   [0, 1, 1, 0, 1],
                   [0, 0, 1, 1, 0]])

# List of graphs
graphs = [graph1, graph2, graph3]

# Calculate pairwise distances
distances = pairwise_graph_distances(graphs)
print('Pairwise distances:\n', distances)

Pairwise distances:
 [[ 0. 14. 10.]
 [14.  0.  8.]
 [10.  8.  0.]]
