# Worksheet 04

Name:  Junyi Li
UID: U13632870

### Topics

- Distance & Similarity

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

in minkowski distance , the parameters p is the parameter that determines the power to which each difference between corresponding elements of the two points is raised, it determines the type of distance and d is the dimension of the vector space.

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

Euclidean distance is the shortest path between source and destination and Manhattan distance is sum of all the real distances between source and destination

Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

when p is very large, he Minkowski distance between A = (0, 0) and B = (1, 1) approaches 1.

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

For p<1, the Minkowski distance is not a metric, because it does not satisfy the triangle inequality.

e) when would you use cosine similarity over the euclidan distance?

When direction matters more than magnitude

f) what does the jaccard distance account for that the manhattan distance doesn't?

Jaccard distance account for the number of elements that are different between two sets, while Manhattan distance only account for the sum of the absolute differences without considering shared or unique elements as sets.

#### Part 2

Consider the following two sentences:

In [1]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [2]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [3]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['hello', 'is', 'Alice', 'name', 'Bob', 'my']
[1, 1, 1, 1, 0, 1]


Let's add a new sentence to our corpus:

In [4]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [5]:
#What is the new union of words used to represent s1, s2, and s3?
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)


['hello', 'hi', 'is', 'Alice', 'Claude', 'name', 'Bob', 'my']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [9]:
v1=[1 if x in s1 else 0 for x in all_words]
v2=[1 if x in s2 else 0 for x in all_words]
v3=[1 if x in s3 else 0 for x in all_words]
print(v1)
print(v2)
print(v3)


[1, 0, 1, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 0, 1, 1, 1]
[0, 1, 1, 0, 1, 1, 0, 1]


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [17]:

def manhattan_distance(v1, v2):
    return sum([abs(x-y) for x,y in zip(v1,v2)])

minimum=100000
for i in range(len(corpus)):
    for j in range(len(corpus)):
        if i!=j:
            v1=[1 if x in corpus[i] else 0 for x in all_words]
            v2=[1 if x in corpus[j] else 0 for x in all_words]
            dist=manhattan_distance(v1,v2)
            if dist<minimum:
                minimum=dist
                s1=corpus[i]
                s2=corpus[j]
print(f'the most similar pairs are "{s1}" and "{s2}"')










the most similar pairs are "hello my name is Alice" and "hello my name is Bob"


d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [ ]:
import numpy as np
corpus=["hi Alice", "hello Claude","Bob my name is Claude","hi Claude my name is Alice","hello Bob"]

all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)

matrix=[[1 if x in s else 0 for x in all_words] for s in corpus]
#print it as a matrix shape
print(np.array(matrix))






['is', 'my', 'Bob', 'Claude', 'hi', 'hello', 'Alice', 'name']
[[0 0 0 0 1 0 1 0]
 [0 0 0 1 0 1 0 0]
 [1 1 1 1 0 0 0 1]
 [1 1 0 1 1 0 1 1]
 [0 0 1 0 0 1 0 0]]


e) How many rows and columns does this matrix have?

In [ ]:

print(len(matrix))
print(len(matrix[0]))



5
8


f) When using the Manhattan distance, which two sentences are the most similar?

In [ ]:
# When using the Manhattan distance, which two sentences are the most similar?
#use a double for loop to compute the distance between each pair of sentences
minimum=10000

for i in range(len(matrix)):
    for j in range(i+1,len(matrix)):
        d=manhattan_distance(matrix[i],matrix[j])
        if d<minimum:
            minimum=d
            i1=i
            i2=j
print(i1,i2)

print(f'the most similar sentences are sentence {i1} and sentence {i2} with a distance of {minimum}')




1 4
the most similar sentences are sentence 1 and sentence 4 with a distance of 2
